import type { SummaryDepth } from '@/types';

export async function downloadSummaryPDF(
  summary: string,
  depth: SummaryDepth,
  date: string
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Meeting Summary', margin, 26);

  const depthLabel = depth.charAt(0).toUpperCase() + depth.slice(1);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`${depthLabel} Summary  ·  ${date}`, margin, 34);
  doc.setTextColor(0, 0, 0);

  doc.setDrawColor(210, 210, 210);
  doc.line(margin, 38, pageWidth - margin, 38);

  // Strip markdown for plain text rendering
  const cleanText = summary
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/^#{1,6}\s/gm, '')
    .replace(/^[-•]\s/gm, '  • ');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  const lines = doc.splitTextToSize(cleanText, contentWidth);
  let y = 46;
  const lineHeight = 6;

  for (const line of lines) {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer on each page
  const totalPages = (doc.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    doc.text('Generated by Transcription Summarizer', margin, pageHeight - 10);
  }

  const timestamp = new Date().toISOString().slice(0, 10);
  doc.save(`meeting-summary-${depth}-${timestamp}.pdf`);
}
